apiVersion: apps/v1
kind: Deployment
metadata:
  name: quingo-frontend
  namespace: quingo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quingo-frontend
  template:
    metadata:
      labels:
        app: quingo-frontend
    spec:
      containers:
        - name: quingo-frontend-container
          image: artem5252/quingo-frontend:latest
          ports:
            - containerPort: 3000

          env:
            - name: PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: PUBLIC_API_URL
